version: '3'
services:
 unifi-controller:
   image: jacobalberty/unifi:stable
   restart: always
   volumes:
     - unifi-lib:/var/lib/unifi'
     - unifi-log:/var/log/unifi'
     - unifi-run:/var/run/unifi'
   ports:
     - '3478:3478/udp'
     - '10001:10001/udp'
     - '6789:6789/tcp'
     - '8080:8080/tcp'
     - '8880:8880/tcp'
     - '8443:8443/tcp'
     - '8843:8843/tcp'
   environment:
     - TZ=America/Denver

volumes:
     unifi-lib:
       driver: local
     unifi-log:
       driver: local
     unifi-run:
       driver: local
